language: java
notifications:
  hipchat:
    rooms:
      secure: Sm2Oq5HqiMhDRO2bPdRv6T1wwNjxcNDd2DRIKE4XqILjR4aqc6IlB+Jq3AvjCVyoJRT0o/DVJS6EiY9wDFHr1JhOUG3V/6q+QpXtD4A5bqwL0d29bfsxj67y6Vt68+9tdnozJCG4bAT19aCVpDBpaTvmTeg6yym9eROJpA6hyitwZgwqQf1uXENoH/MO2Ut9HFqtgM3W1rAqYpew+GMuGSVngyfVGTTI8Nf0ByqooHgDZc3EIhKJvDj1tbmTWoMQprvN7A7X0rLTYs1KX47zSXcNFgMI9bYgRpqeXbI7iS3iJzF4gkS9L+Q9/+r7ujkpcNj1QHebFzkbKjdhk+l9Nz8CPefNQ0uGDBCkaMTuroVhnTkMl397GcrQ5OcEjZmM1CqQjiVqn5pvQLbgQ//DuX6Lug1RpD2eCw1/IVf4jBPDaIKd4WvL1cMmokQLnRXopbYODsQAvA5ZH39ki2IgGsVDxFixrigPU7KSb86116zB4UEvM8p8zJHTskCbXL5eIU0pG8LexP/rwv14xm81pIngYvWpsKrFC1k7d3z2EO0cH2Kvh7D0S6YopM2HmqeqjMhHqT748nognusg+0yzSB9u0vgysVFNGxNCNErgr1XzYQAqO97pK4rY+yj25PmT+b/iszq95TJEWdS8/RLG/JLXMEkMtyIJ1o5HGSQO8bA=
deploy:
  provider: releases
  api_key:
    secure: IDZq6GzHHK33EssfQ9P8WH/U59foaidaVD9X7vmSeG/JpdpzKSzhRmWG1j7nzoUXxvCKCBsa+TYp9TIr2MIfKnb14u3pLu+G6Ic0DKZEETxopSRUqw/eZCjWmwNaN7FT0EMUQP1ge00R7oHF4/dqkKJCZ7lH7tuqlZhCuzejWrqUst0IIiEyKDnM9oenbrmnYfmqw9Gk21hegqAi5LpGjVwgzpYpE2vPTztookf8K62wdrTp7WvD/heu0/svxrqQKR91aiYOEzIqlYWmfAACBvkc8ITZ5RRnUocx9wfHDMUJakRV6sJSiv4CNdzQVjCXVEdnk6Z4i6r3gg9/Wk6BjKXQVykb0up3sCS/YysZKKxDXCgZK8mosWau3b/4LplIfbeVbkR8sztVZ+NZ7AaLKp09j9793/YIZ8ojYDExwdX/Q1O54TSk+JUN3vIs+4guujkCXOIO4iAVewZySFv4babjzLbirfemHszTMb0YtXm3F07s+7BGfg6OGwo37F8CK51ufskQHU0V4aB4425aqbLd5VyI/DbUXgWTApEk939kuXocPUuNjKKQLX1kyMEjX6aDSjJPiWUG4Re6M9RRj+Z5TXPJy07eMjAw1lybC78qm8VQ6CDWwuhMAHVWCyZrUYk6GU7hqsbsdHaT2YlTYOf0te61grPCoAh3E1FqPkw=
  file_glob: true
  file: build/distributions/*
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
    repo: xebialabs-community/xld-folder-plugin
